[pytest]
addopts = 
    --headed 
    --browser chromium 
    --browser firefox
    --html=reports/full_report.html 
    --self-contained-html
    --tracing on
    --video on-first-retry
testpaths = step_definitions